version: "3.8"

services:
    db:
        image: postgres:10.13
        restart: unless-stopped
        volumes:
            - ./docker/db/:/var/lib/postgresql/
        env_file:
            - .env

    php-fpm:
        image: bitnami/php-fpm:latest
        ports:
            - "9000:9000"
        volumes:
            - ./htdocs3:/var/www/html
            - ./docker/php/conf.d/:/opt/bitnami/php/etc/conf.d/:ro
        environment:
            - TZ=UTC
        env_file:
            - .env
        depends_on:
            - db

    web:
        image: bitnami/nginx:latest
        # hostname: bcmsa.devel
        ports:
            # - "443:8443"
            - "8080:8080"
        volumes:
            - ./docker/nginx/default.conf:/opt/bitnami/nginx/conf/server_blocks/bcmsa.devel.conf:ro
            - ./docker/nginx/certs:/certs:ro
            - ./htdocs3:/var/www/html:cached
        environment:
            - TZ=UTC
        env_file:
            - .env
        depends_on:
            - php-fpm
