---
kind: Template
apiVersion: v1
labels:
  template: nmp-msa-frontend-template
metadata:
  name: frontend-dc
  creationTimestamp:
parameters:
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment Name
    required: true
  - name: CPU_REQUEST
    displayName: Requested CPU
    description: Requested CPU
    required: true
  - name: CPU_LIMIT
    displayName: CPU upper limit
    description: CPU upper limit
    required: true
  - name: MEMORY_REQUEST
    displayName: Requested memory
    description: Requested memory
    required: true
  - name: MEMORY_LIMIT
    displayName: Memory upper limit
    description: Memory upper limit
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: nmp-msa-frontend
      labels:
        name: nmp-msa-frontend
        app: nmp-msa
        env: ${ENV_NAME}
    spec:
      ports:
        - name: web-frontend
          protocol: TCP
          port: 5001
          targetPort: 5001
      selector:
        name: nmp-msa-frontend
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: nmp-msa-frontend
      labels:
        name: nmp-msa-frontend
        app: nmp-msa
        role: frontend
        env: ${ENV_NAME}
    spec:
      replicas: 1
      strategy:
        type: Recreate
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - frontend
            from:
              kind: ImageStreamTag
              name: 'nmp-msa-frontend:latest'
              namespace: agri-nmp-dev
            type: imageChange
        - type: ConfigChange
      test: false
      selector:
        name: nmp-msa-frontend
      template:
        metadata:
          creationTimestamp:
          labels:
            name: nmp-msa-frontend
        spec:
          containers:
            - name: frontend
              image: " "
              ports:
                - containerPort: 5001
                  protocol: TCP
              env:
                - name: NPM_RUN
                  value: 'serve'
              resources:
                request:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
              readinessProbe:
                tcpSocket:
                  port: 5001
                initialDelaySeconds: 2
                timeoutSeconds: 2
                periodSeconds: 30
                successThreshold: 1
                failureThreshold: 3
              imagePullPolicy: IfNotPresent
              securityContext:
                capabilities: {}
                privileged: false
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
    status: {}
